### ISSUE TITLE
Debian Bullseye support

### ISSUE THREAD

**Issue by zejar** [Erik-Lamers1/vnet-manager#36]
In order to setup VNet-manager on Debian Bullseye only a few changes need to be made. VNet-manager seems to work on Bullseye at least up to (and including) lab2 of INR ;-)

In [vnet_manager/settings/base.py](https://github.com/Erik-Lamers1/vnet-manager/blob/master/vnet_manager/settings/base.py) `bullseye` needs to be added to the `supported_operating_systems` (`PROVIDERS.lxc.supported_operating_systems`).

In [vnet_manager/environment/host.py](https://github.com/Erik-Lamers1/vnet-manager/blob/master/vnet_manager/environment/host.py) the function `check_for_installed_packages` checks if all `required_host_packages` are present in the cache. My guess is that this is the `apt` cache. On Ubuntu this check works for `lxd` which has been installed using Snap, but on Debian it does not detect the `lxd` program to be installed when using Snap. Perhaps there is another proper way to check if `lxd` has been installed on Debian instead of relying on the `apt` cache.

A workaround to get vnet-manager to work on Debian (for future students who want to make use of Debian instead of Ubuntu) is by removing the `lxd` dependency from the `required_host_packages` setting (`PROVIDER.lxc.required_host_packages`) in [vnet_manager/settings/base.py](https://github.com/Erik-Lamers1/vnet-manager/blob/master/vnet_manager/settings/base.py).

In order to make use of the `ubuntu20.04.yaml` pre-seed file one can install ZFS relatively easy as well (by installing the `linux-headers-amd64 ` and `zfsutils-linux` packages).

**Comment by Erik-Lamers1** [comment]
I would not recommend editing the base settings in a locally cloned repo unless there is no other way. The settings module in vnet-manager is built to mimic the settings module as it is used with [django](https://docs.djangoproject.com/en/3.2/topics/settings/). If you want to change something locally you can create a local python file that extends upon the base settings like this;

```python
from vnet_manager.settings.base import *

PROVIDERS["lxc"]["supported_operating_systems"].append("bullseye")
```
```bash
$ export PYTHONPATH=.
$ export SETTINGS_MODULE=<myfile>
```
This way there is also no need to install anything locally, as a pip installed version of vnet-manager will pick up these settings if `SETTINGS_MODULE` has been set in the environment.
The reason I have this `supported_operating_systems` in the first place is that these are the OS'es vnet-manager is actually tested on. For future versions, it might be enough to simply change this to a warning message if running on an untested OS instead of requiring a setting change.

The `apt`  thing got me thinking. The reason I included the `apt` package checks is to make the installation and usage of vnet-manager a bit more foolproof. This way the program could tell the user exactly what software package(s) are missing if any. But on the other hand, this feature does make it harder to run vnet-manager on other distros. So, maybe it is a better idea to just extend the README.md or make an INSTALLATION.md with the required software for vnet-manager to run.
