### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by arno481** [Erik-Lamers1/vnet-manager#9]
````
# python3 setup.py install
...
Best match: ws4py 0.5.1
Processing ws4py-0.5.1.tar.gz
Writing /tmp/easy_install-l7xa9n7j/ws4py-0.5.1/setup.cfg
Running ws4py-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-l7xa9n7j/ws4py-0.5.1/egg-dist-tmp-i1gk3rym
  File "build/bdist.linux-x86_64/egg/ws4py/server/tulipserver.py", line 43
    f = asyncio.async(self.handle_initial_handshake())
                ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/ws4py/async_websocket.py", line 87
    asyncio.async(closeit())
            ^
SyntaxError: invalid syntax
````

CU,
          Arno

**Comment by Erik-Lamers1** [comment]
Which python version are you running? 
I tested setup.py for python3.6.9 and python3.8.5.
Which are the current versions for Ubuntu 18.04 and 20.04 at the moment.

**Comment by arno481** [comment]
Ubuntu 20.04:

Python 3.8.5 (default, Jul 28 2020, 12:59:40) 

Does not seem to affect basic operation. My RIPng test works ;o)

**Comment by Erik-Lamers1** [comment]
I have been able to replicate the issue on a fresh 20.04 install. But it seems that this is not causing any functions of VNet-manager to fail. 
The only related issues I have found were referring to Python3.7 on Debian Buster, which since have been fixed.
This seems like a ws4py issue to me, which as long as it doesn't break any functionality is not a problem.

**Comment by Erik-Lamers1** [comment]
Stale, closing
